name: Cherry-Pick to Dev Branch

on:
  push:
    branches:
      - "staging_v*"

env:
  GH_TOKEN: ${{ github.token }}
jobs:
  cherry-pick:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: "development"
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Get Commit Author
        id: get_author
        run: |
          echo ::set-output name=AUTHOR::$(git --no-pager log -1 --pretty="%an")

      - name: Fetch and Merge from Staging Branch
        run: |
          # Create a temporary branch for merging changes
          git checkout -b hotfix/${{github.sha}}
          git rebase origin/${{github.ref_name}}
          git push origin hotfix/${{github.sha}}

      - name: Push and Create Pull Request with GH CLI
        run: |
          echo "Creating Pull Request using GitHub CLI"
          PR_URL=$(gh pr create \
            --title "Merging changes from staging_v*" \
            --body "This PR merges changes from the staging_v* branch." \
            --repo ${{ github.repository }} \
            --base development \
            --head hotfix/${{github.sha}} | awk '/https:\/\/github.com/{print $0}')
          gh pr edit "$PR_URL" --add-reviewer "${{ steps.get_author.outputs.AUTHOR }}"